# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       qmlmusicplayer

# >> macros
# << macros

Summary:    Nemo Mobile Music Player
Version:    2.0.4
Release:    1.1.Nemo
Group:      Applications/Multimedia
License:    GPLv2
Source0:    %{name}-%{version}.tar.bz2
Source100:  qmlmusicplayer.yaml
BuildRequires:  pkgconfig(QtDeclarative)
BuildRequires:  pkgconfig(QtMultimediaKit)
BuildRequires:  pkgconfig(QtOpenGL)
BuildRequires:  desktop-file-utils
Provides:   org.pycage.musicshelf > 1.0.1
Obsoletes:   org.pycage.musicshelf <= 1.0.1

%description
Music Player for Nemo Mobile


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
# >> files
/opt/qmlmediaplayer/bin/qmlmediaplayer
%{_datadir}/applications/qmlmediaplayer.desktop
%{_datadir}/pixmaps/qmlmediaplayer.png
# << files
%changelog
* Mon May 20 2013 Robin Burchell <robin+git@viroteck.net> - 2.0.4
- [qmlmusicplayer] Rename title to be shorter.
* Mon May 20 2013 Robin Burchell <viroteck@viroteck.net> - 2.0.3
- [qmlmusicplayer] Declare supported MimeType in Desktop Entry
* Wed Apr  3 2013 Robin Burchell <robin+git@viroteck.net> - 2.0.2
- [qmlmusicplayer] Add dependency to QtOpenGL. It's implicitly pulled somewhere.
- [qmlmusicplayer] Convert to git packaging
* Thu Feb 21 2013 Robin Burchell <robin+mer@viroteck.net> - 2.0.1
- Initial packaging, replacing musicshelf
